
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ACER
 */
public class Frame1 extends javax.swing.JFrame {

    /**
     * Creates new form Frame1
     */
    public Frame1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tbalok = new javax.swing.JTextField();
        pbalok = new javax.swing.JTextField();
        lbalok = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        BtnBalok = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jsisi = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        BtnKubus = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        tfJariBola = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        BtnBola = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel6.setBackground(new java.awt.Color(204, 153, 255));

        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        jPanel4.setBackground(new java.awt.Color(255, 153, 255));
        jPanel4.setLayout(null);

        jLabel8.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabel8.setText("Masukkan Tinggi : ");
        jPanel4.add(jLabel8);
        jLabel8.setBounds(20, 170, 180, 30);

        jLabel9.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabel9.setText("Masukkan Panjang : ");
        jPanel4.add(jLabel9);
        jLabel9.setBounds(20, 50, 180, 30);

        jLabel10.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabel10.setText("Masukkan Lebar : ");
        jPanel4.add(jLabel10);
        jLabel10.setBounds(20, 110, 180, 30);
        jPanel4.add(tbalok);
        tbalok.setBounds(190, 170, 200, 30);
        jPanel4.add(pbalok);
        pbalok.setBounds(190, 50, 200, 30);
        jPanel4.add(lbalok);
        lbalok.setBounds(190, 110, 200, 30);

        jLabel11.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jLabel11.setText("cm");
        jPanel4.add(jLabel11);
        jLabel11.setBounds(410, 180, 40, 20);

        jLabel12.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jLabel12.setText("cm");
        jPanel4.add(jLabel12);
        jLabel12.setBounds(410, 50, 40, 20);

        jLabel13.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jLabel13.setText("cm");
        jPanel4.add(jLabel13);
        jLabel13.setBounds(410, 120, 40, 20);

        BtnBalok.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        BtnBalok.setText("HITUNG");
        BtnBalok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBalokActionPerformed(evt);
            }
        });
        jPanel4.add(BtnBalok);
        BtnBalok.setBounds(200, 250, 190, 50);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 495, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Balok", jPanel1);

        jPanel5.setBackground(new java.awt.Color(255, 255, 153));
        jPanel5.setLayout(null);

        jLabel15.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabel15.setText("Masukkan Sisi : ");
        jPanel5.add(jLabel15);
        jLabel15.setBounds(20, 50, 180, 30);
        jPanel5.add(jsisi);
        jsisi.setBounds(190, 50, 200, 30);

        jLabel18.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jLabel18.setText("cm");
        jPanel5.add(jLabel18);
        jLabel18.setBounds(410, 50, 40, 20);

        BtnKubus.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        BtnKubus.setText("HITUNG");
        BtnKubus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnKubusActionPerformed(evt);
            }
        });
        jPanel5.add(BtnKubus);
        BtnKubus.setBounds(200, 250, 190, 50);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 517, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 311, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Kubus", jPanel2);

        jPanel3.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabel3.setText("Masukkan Jari-Jari : ");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(20, 50, 210, 30);
        jPanel3.add(tfJariBola);
        tfJariBola.setBounds(230, 50, 160, 30);

        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jLabel6.setText("cm");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(410, 50, 40, 20);

        BtnBola.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        BtnBola.setText("HITUNG");
        BtnBola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBolaActionPerformed(evt);
            }
        });
        jPanel3.add(BtnBola);
        BtnBola.setBounds(200, 250, 190, 50);

        jPanel7.setBackground(new java.awt.Color(153, 255, 204));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 510, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 330, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel7);
        jPanel7.setBounds(0, 0, 510, 330);

        jTabbedPane1.addTab("Bola", jPanel3);

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel1.setText("Program Penghitung Volume Bangun Ruang");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(67, Short.MAX_VALUE))
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel6);
        jPanel6.setBounds(0, 0, 510, 420);

        setBounds(0, 0, 525, 464);
    }// </editor-fold>//GEN-END:initComponents

    private void BtnKubusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnKubusActionPerformed
    int sisi;
    sisi=Integer.parseInt(jsisi.getText());
    int hasil=sisi*sisi*sisi;
        try {
            JOptionPane.showMessageDialog(null, "Volume kubus Adalah :"
                    + hasil + "cm3","", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error" + e, "Gagal",
                    JOptionPane.WARNING_MESSAGE);
        }
// TODO add your handling code here:
    }//GEN-LAST:event_BtnKubusActionPerformed

    private void BtnBolaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBolaActionPerformed
    int jari = Integer.parseInt(tfJariBola.getText());
        float hasil1=(float) (4/3*Math.PI*jari*jari*jari);
try{
JOptionPane.showMessageDialog(null,"Volume Permukaan Bola Adalah :"
+hasil1+"cm3","",JOptionPane.INFORMATION_MESSAGE);
} catch (Exception e) {
JOptionPane.showMessageDialog(null,"Error"+e,"Gagal",
        JOptionPane.WARNING_MESSAGE);
}
// TODO add your handling code here:
    }//GEN-LAST:event_BtnBolaActionPerformed

    private void BtnBalokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBalokActionPerformed
                // TODO add your handling code here:
        int panjang, lebar, tinggi;
        panjang=Integer.parseInt(pbalok.getText());
        lebar=Integer.parseInt(lbalok.getText());
        tinggi=Integer.parseInt(tbalok.getText());
        int hasil=panjang*lebar*tinggi;
        try {
            JOptionPane.showMessageDialog(null,"Volume Balok Adalah :"+hasil+" cm3", "" , JOptionPane.INFORMATION_MESSAGE);
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, "Error:"+e,"Gagsl",
                    JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_BtnBalokActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBalok;
    private javax.swing.JButton BtnBola;
    private javax.swing.JButton BtnKubus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jsisi;
    private javax.swing.JTextField lbalok;
    private javax.swing.JTextField pbalok;
    private javax.swing.JTextField tbalok;
    private javax.swing.JTextField tfJariBola;
    // End of variables declaration//GEN-END:variables
}
